name: xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_swiper_view: ^1.1.8
  dio: ^5.4.3+1
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.3

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assest/images/xiaomiBanner.png
    - assest/images/2.0x/xiaomiBanner.png
    - assest/images/3.0x/xiaomiBanner.png
    - assest/images/xiaomiBanner2.png
    - assest/images/2.0x/xiaomiBanner2.png
    - assest/images/3.0x/xiaomiBanner2.png
    - assest/images/xiaomi.png
    - assest/images/2.0x/xiaomi.png
    - assest/images/3.0x/xiaomi.png
    - assest/xiaomi.png

